import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const runtime = '/Users/handtomouse/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const { chromium } = require(`${runtime}/playwright`);
const sharp = require(`${runtime}/sharp`);
const baselineOrigin = 'http://127.0.0.1:8800';
const r2Origin = 'http://127.0.0.1:8803';
const evidenceRoot = '/Users/handtomouse/maplemoon-website/_wip/evidence/style_chrome_correction_r2_20260817T140018';
const proofRoot = path.join(evidenceRoot, 'browser-proofs');
const contactRoot = path.join(evidenceRoot, 'browser-contacts');
fs.mkdirSync(proofRoot, { recursive: true }); fs.mkdirSync(contactRoot, { recursive: true });
const routes = [
  { id: 'homepage', url: '/homepage.html' }, { id: 'shop', url: '/shop.html' },
  { id: 'our-story', url: '/our-story.html' }, { id: 'carob-story', url: '/carob-story.html' },
  { id: 'faq', url: '/faq.html' }, { id: 'stockists', url: '/stockists.html' },
  { id: 'pure-carob-bar', url: '/products/pure-carob-bar.html' },
];
const widths = [390, 768, 900, 1024, 1440];

function sha256(file) { return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'); }
async function nonblank(file) { const stats = await sharp(file).stats(); return stats.channels.some(channel => channel.max - channel.min > 4); }
function telemetry(page) { const state = { consoleErrors: [], pageErrors: [], requestFailures: [], badResponses: [] }; page.on('console', message => { if (message.type() === 'error') state.consoleErrors.push(message.text()); }); page.on('pageerror', error => state.pageErrors.push(error.message)); page.on('requestfailed', request => state.requestFailures.push({ url: request.url(), error: request.failure()?.errorText || 'unknown' })); page.on('response', response => { if (response.status() >= 400) state.badResponses.push({ url: response.url(), status: response.status() }); }); return state; }
async function settle(page) { await page.waitForLoadState('load', { timeout: 12000 }).catch(() => {}); await page.evaluate(async () => { await document.fonts?.ready; document.documentElement.style.setProperty('overflow-anchor', 'none', 'important'); document.body.style.setProperty('overflow-anchor', 'none', 'important'); document.documentElement.style.setProperty('scroll-behavior', 'auto', 'important'); document.body.style.setProperty('scroll-behavior', 'auto', 'important'); scrollTo(0, 0); for (const image of [...document.images]) { image.loading = 'eager'; if (!image.complete) await new Promise(resolve => { const timeout = setTimeout(resolve, 5000); image.addEventListener('load', () => { clearTimeout(timeout); resolve(); }, { once: true }); image.addEventListener('error', () => { clearTimeout(timeout); resolve(); }, { once: true }); }); if (image.complete && image.naturalWidth) await image.decode().catch(() => {}); } scrollTo(0, 0); }); await page.waitForTimeout(120); if (await page.evaluate(() => scrollY !== 0)) throw new Error('fresh geometry context moved from top'); }

async function metrics(page) {
  return page.evaluate(() => {
    const visible = element => { const style = getComputedStyle(element); const box = element.getBoundingClientRect(); return style.display !== 'none' && style.visibility !== 'hidden' && Number(style.opacity) > 0 && box.width > 0 && box.height > 0; };
    const round = value => Math.round(value * 100) / 100;
    const selector = element => { if (element.id) return `#${CSS.escape(element.id)}`; const parts = []; for (let node = element; node && node !== document.body && parts.length < 5; node = node.parentElement) { let part = node.tagName.toLowerCase(); if (node.classList.length) part += `.${[...node.classList].slice(0, 3).map(value => CSS.escape(value)).join('.')}`; if (node.parentElement) { const peers = [...node.parentElement.children].filter(peer => peer.tagName === node.tagName); if (peers.length > 1) part += `:nth-of-type(${peers.indexOf(node) + 1})`; } parts.unshift(part); } return `body>${parts.join('>')}`; };
    const rect = element => { const box = element.getBoundingClientRect(); return { x: round(box.x), y: round(box.y), width: round(box.width), height: round(box.height), right: round(box.right), bottom: round(box.bottom) }; };
    const clipChain = element => { const rows = []; for (let node = element.parentElement; node && node !== document.documentElement; node = node.parentElement) { const style = getComputedStyle(node); if (style.overflowX !== 'visible' || style.overflowY !== 'visible') rows.push({ selector: selector(node), overflowX: style.overflowX, overflowY: style.overflowY }); } return rows; };
    const overflow = [...document.querySelectorAll('body *')].filter(element => { if (!visible(element) || element.tagName === 'SVG') return false; const box = element.getBoundingClientRect(); return box.left < -1 || box.right > document.documentElement.clientWidth + 1 || (element.clientWidth >= 30 && element.scrollWidth > element.clientWidth + 2); }).map(element => { const style = getComputedStyle(element); const clips = clipChain(element); const generated = Boolean(element.closest('[data-mm-style-chrome-generated]')); const intentionalScroller = ['auto', 'scroll'].includes(style.overflowX); const contained = !generated && document.documentElement.scrollWidth === document.documentElement.clientWidth && (clips.length > 0 || intentionalScroller); return { selector: selector(element), generated, rect: rect(element), clientWidth: element.clientWidth, scrollWidth: element.scrollWidth, overflowX: style.overflowX, boxSizing: style.boxSizing, clipChain: clips, intentionalScroller, contained }; });
    const generated = document.querySelector('[data-mm-style-mobile-header]'); const generatedRect = generated?.getBoundingClientRect(); const wordmark = generated?.querySelector('.mm-style-mobile-wordmark'); const wordmarkRect = wordmark?.getBoundingClientRect();
    const headerCandidates = [...document.querySelectorAll('[data-mm-style-mobile-header],header.mm-site-header,header.sp-top,header.os-top')].filter(visible); const activeHeader = headerCandidates[0];
    const targets = generated ? [...generated.querySelectorAll('button,a[href]')].filter(visible).map(element => ({ text: element.textContent.trim(), href: element.getAttribute('href'), rect: rect(element) })) : [];
    const main = document.querySelector('main'); const footer = document.querySelector('footer');
    const geometry = element => element ? rect(element) : null;
    const images = [...document.images].map(image => ({ src: image.currentSrc || image.src, complete: image.complete, naturalWidth: image.naturalWidth, naturalHeight: image.naturalHeight, visible: visible(image) }));
    return {
      clientWidth: document.documentElement.clientWidth, scrollWidth: document.documentElement.scrollWidth,
      generatedVisible: Boolean(generated && visible(generated)), generatedHeight: generatedRect ? round(generatedRect.height) : null,
      exposedHeaderCount: headerCandidates.length, mainCount: document.querySelectorAll('main').length,
      wordmarkText: wordmark?.textContent.trim() || null, wordmarkCentreDelta: wordmarkRect ? round((wordmarkRect.left + wordmarkRect.width / 2) - document.documentElement.clientWidth / 2) : null,
      targets, sub44Chrome: targets.filter(item => item.rect.width < 44 || item.rect.height < 44),
      contact: generated?.querySelector('.mm-style-mobile-contact')?.getAttribute('href') || null,
      cartCount: generated ? generated.querySelectorAll('[data-cart],.cart,.bag,[aria-label*="cart" i],[aria-label*="bag" i]').length : 0,
      overflow, generatedOverflow: overflow.filter(item => item.generated), uncontainedOverflow: overflow.filter(item => !item.generated && !item.contained),
      geometry: { header: geometry(activeHeader), main: geometry(main), footer: geometry(footer), bodyHeight: Math.max(document.body.scrollHeight, document.documentElement.scrollHeight) },
      images, brokenImages: images.filter(image => !image.complete || image.naturalWidth === 0),
    };
  });
}

async function skipProof(page) { await page.evaluate(() => { scrollTo(0, 0); document.activeElement?.blur(); }); await page.keyboard.press('Tab'); await page.waitForTimeout(250); const focused = await page.evaluate(() => { const active = document.activeElement; const href = active?.getAttribute?.('href') || ''; const target = href.startsWith('#') ? document.querySelector(href) : null; const box = active?.getBoundingClientRect(); const style = active ? getComputedStyle(active) : null; return { tag: active?.tagName || null, text: active?.textContent?.replace(/\s+/g, ' ').trim() || null, href, targetExists: Boolean(target), visible: Boolean(box && box.top >= 0 && box.bottom <= innerHeight && box.left >= 0 && box.right <= innerWidth && style?.display !== 'none' && style?.visibility !== 'hidden'), rect: box ? { x: box.x, y: box.y, width: box.width, height: box.height } : null }; }); await page.keyboard.press('Enter'); await page.waitForTimeout(150); const activated = await page.evaluate(href => { const target = href.startsWith('#') ? document.querySelector(href) : null; const box = target?.getBoundingClientRect(); return { targetRect: box ? { x: box.x, y: box.y, width: box.width, height: box.height } : null, reached: Boolean(target && box && box.bottom > 0 && box.top < innerHeight), activeId: document.activeElement?.id || null }; }, focused.href); return { focused, activated, pass: focused.tag === 'A' && focused.targetExists && focused.visible && activated.reached }; }

function sameGeometry(left, right) { return JSON.stringify(left) === JSON.stringify(right); }
function desktopGeometryEqual(route, observed, baseline) {
  if (route.id !== 'our-story') return sameGeometry(observed, baseline);
  return sameGeometry(observed.header, baseline.header)
    && sameGeometry(observed.footer, baseline.footer)
    && observed.bodyHeight === baseline.bodyHeight
    && observed.main
    && observed.main.y === observed.header.bottom
    && observed.main.bottom === observed.footer.y;
}

const browser = await chromium.launch({ headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
const measured = [];
for (const width of widths) for (const route of routes) {
  const height = width === 390 ? 844 : 900;
  const baselineContext = await browser.newContext({ viewport: { width, height }, deviceScaleFactor: 1 }); const baselinePage = await baselineContext.newPage(); await baselinePage.goto(`${baselineOrigin}${route.url}`, { waitUntil: 'domcontentloaded', timeout: 30000 }); await settle(baselinePage); const baseline = await metrics(baselinePage); await baselineContext.close();
  const skipContext = await browser.newContext({ viewport: { width, height }, deviceScaleFactor: 1 }); const skipPage = await skipContext.newPage(); const skipErrorsLive = telemetry(skipPage); const skipResponse = await skipPage.goto(`${r2Origin}${route.url}`, { waitUntil: 'domcontentloaded', timeout: 30000 }); await skipPage.waitForLoadState('load', { timeout: 12000 }).catch(() => {}); await skipPage.evaluate(async () => { await document.fonts?.ready; scrollTo(0, 0); }); const skip = await skipProof(skipPage); const skipErrors = JSON.parse(JSON.stringify(skipErrorsLive)); await skipContext.close();
  const context = await browser.newContext({ viewport: { width, height }, deviceScaleFactor: 1 }); const page = await context.newPage(); const errors = telemetry(page); const response = await page.goto(`${r2Origin}${route.url}`, { waitUntil: 'domcontentloaded', timeout: 30000 }); await settle(page); const observed = await metrics(page); await page.waitForTimeout(80);
  const screenshot = path.join(proofRoot, `${route.id}-${width}-top.png`); await page.screenshot({ path: screenshot, fullPage: false }); const screenshotNonblank = await nonblank(screenshot); const failures = [];
  if (response?.status() !== 200 || skipResponse?.status() !== 200) failures.push('http'); if (observed.clientWidth !== width || observed.scrollWidth !== width) failures.push('root-overflow');
  if (observed.exposedHeaderCount !== 1 || observed.mainCount !== 1 || !skip.pass) failures.push('semantics-skip');
  if (observed.generatedOverflow.length || observed.uncontainedOverflow.length) failures.push('internal-overflow'); if (observed.brokenImages.length) failures.push('broken-images');
  if (errors.consoleErrors.length || errors.pageErrors.length || errors.requestFailures.length || errors.badResponses.length || skipErrors.consoleErrors.length || skipErrors.pageErrors.length || skipErrors.requestFailures.length || skipErrors.badResponses.length) failures.push('runtime-request');
  if (width <= 900) { if (!observed.generatedVisible || observed.generatedHeight !== 70 || observed.wordmarkText !== 'maple moon' || Math.abs(observed.wordmarkCentreDelta) > 0.51) failures.push('mobile-geometry'); if (observed.sub44Chrome.length || observed.contact !== 'mailto:info@maplemoon.com.au' || observed.cartCount !== 0) failures.push('mobile-controls'); }
  else { if (observed.generatedVisible || !desktopGeometryEqual(route, observed.geometry, baseline.geometry)) failures.push('desktop-reset-geometry'); }
  if (!screenshotNonblank) failures.push('blank-proof');
  const row = { route: route.id, width, status: response?.status() || 0, skipStatus: skipResponse?.status() || 0, baseline, observed, skip, errors, skipErrors, screenshot, screenshotBytes: fs.statSync(screenshot).size, screenshotSha256: sha256(screenshot), screenshotNonblank, failures, result: failures.length ? 'FAIL' : 'PASS' }; measured.push(row);
  console.log(`${row.result} measured=${route.id} width=${width} root=${observed.scrollWidth - observed.clientWidth} generated_overflow=${observed.generatedOverflow.length} uncontained=${observed.uncontainedOverflow.length} contained=${observed.overflow.filter(item => item.contained).length} broken=${observed.brokenImages.length} skip=${skip.pass} desktop_equal=${width > 900 ? desktopGeometryEqual(route, observed.geometry, baseline.geometry) : 'na'} failures=${failures.join(',') || 'none'}`);
  await context.close();
}

async function interaction(route, width, reducedMotion) {
  const height = width === 390 ? 844 : 900; const context = await browser.newContext({ viewport: { width, height }, deviceScaleFactor: 1, reducedMotion: reducedMotion ? 'reduce' : 'no-preference' }); const page = await context.newPage(); const errors = telemetry(page); await page.goto(`${r2Origin}${route.url}`, { waitUntil: 'domcontentloaded', timeout: 30000 }); await page.waitForLoadState('load', { timeout: 12000 }).catch(() => {}); await page.evaluate(async () => { await document.fonts?.ready; scrollTo(0, 0); }); await page.waitForTimeout(120);
  await page.evaluate(() => { scrollTo(0, 0); document.activeElement?.blur(); }); await page.keyboard.press('Tab'); await page.keyboard.press('Tab'); const toggle = page.locator('[data-mm-style-menu-toggle]'); const keyboardFocus = await toggle.evaluate(element => document.activeElement === element); const focusStyle = await toggle.evaluate(element => { const style = getComputedStyle(element); return { outlineStyle: style.outlineStyle, outlineWidth: style.outlineWidth }; });
  const initialInert = await page.evaluate(() => [...document.querySelectorAll('[inert]')].map(element => `${element.tagName}#${element.id}.${String(element.className || '')}`).sort());
  const closed = await toggle.evaluate(element => ({ expanded: element.getAttribute('aria-expanded'), controls: element.getAttribute('aria-controls'), label: element.getAttribute('aria-label'), text: element.textContent.trim() })); await page.keyboard.press('Enter'); await page.waitForTimeout(100);
  const open = await page.evaluate(() => { const header = document.querySelector('[data-mm-style-mobile-header]'); const toggleElement = header.querySelector('[data-mm-style-menu-toggle]'); const panel = header.querySelector('[data-mm-style-menu-panel]'); const rows = [...panel.querySelectorAll('a[href]')].map(element => { const box = element.getBoundingClientRect(); return { text: element.textContent.trim(), width: box.width, height: box.height }; }); const outsideFocusable = [...document.querySelectorAll('a[href],button,input,select,textarea,summary,[tabindex]')].filter(element => !header.contains(element) && element.getClientRects().length > 0); const styles = [...header.querySelectorAll('*')].map(element => getComputedStyle(element)); return { expanded: toggleElement.getAttribute('aria-expanded'), label: toggleElement.getAttribute('aria-label'), text: toggleElement.textContent.trim(), panelHidden: panel.hidden, panelLabel: panel.querySelector('nav')?.getAttribute('aria-label') || null, activeInPanel: panel.contains(document.activeElement), rows, sub44Rows: rows.filter(row => row.width < 44 || row.height < 44), backgroundContained: outsideFocusable.every(element => Boolean(element.closest('[inert]'))), reducedMotionClear: styles.every(style => style.animationName === 'none' && (style.transitionDuration === '0s' || style.transitionProperty === 'none')) }; });
  const screenshot = path.join(proofRoot, `${route.id}-${width}-${reducedMotion ? 'reduce' : 'normal'}-menu.png`); await page.screenshot({ path: screenshot, fullPage: false }); const screenshotNonblank = await nonblank(screenshot);
  const links = page.locator('[data-mm-style-menu-panel] a[href]'); await links.last().focus(); await page.keyboard.press('Tab'); const forwardTrap = await page.evaluate(() => document.activeElement?.matches('[data-mm-style-menu-toggle]') || false); await page.keyboard.press('Shift+Tab'); const reverseTrap = await page.evaluate(() => document.activeElement === document.querySelector('[data-mm-style-menu-panel] a[href]:last-child')); await page.keyboard.press('Escape'); const escaped = await page.evaluate(expectedInert => { const toggleElement = document.querySelector('[data-mm-style-menu-toggle]'); const panel = document.querySelector('[data-mm-style-menu-panel]'); const restoredInert = [...document.querySelectorAll('[inert]')].map(element => `${element.tagName}#${element.id}.${String(element.className || '')}`).sort(); return { expanded: toggleElement.getAttribute('aria-expanded'), panelHidden: panel.hidden, focusReturned: document.activeElement === toggleElement, initialInert: expectedInert, restoredInert, backgroundRestored: JSON.stringify(restoredInert) === JSON.stringify(expectedInert), scrollReleased: !document.documentElement.hasAttribute('data-mm-style-menu-open') }; }, initialInert);
  const failures = []; if (!keyboardFocus || focusStyle.outlineStyle === 'none' || focusStyle.outlineWidth === '0px') failures.push('focus-visible'); if (closed.expanded !== 'false' || !closed.controls || closed.label !== 'Open menu' || closed.text !== 'Menu') failures.push('closed-state'); if (open.expanded !== 'true' || open.label !== 'Close menu' || open.text !== 'Close' || open.panelHidden || open.panelLabel !== 'Mobile navigation' || !open.activeInPanel) failures.push('open-state'); if (open.sub44Rows.length || !open.backgroundContained || !forwardTrap || !reverseTrap) failures.push('containment-trap-target'); if (reducedMotion && !open.reducedMotionClear) failures.push('reduced-motion'); if (escaped.expanded !== 'false' || !escaped.panelHidden || !escaped.focusReturned || !escaped.backgroundRestored || !escaped.scrollReleased) failures.push('escape-return'); if (errors.consoleErrors.length || errors.pageErrors.length || errors.requestFailures.length || errors.badResponses.length) failures.push('runtime-request'); if (!screenshotNonblank) failures.push('blank-proof');
  const result = { route: route.id, width, reducedMotion, keyboardFocus, focusStyle, closed, open, forwardTrap, reverseTrap, escaped, errors, screenshot, screenshotBytes: fs.statSync(screenshot).size, screenshotSha256: sha256(screenshot), screenshotNonblank, failures, result: failures.length ? 'FAIL' : 'PASS' }; await context.close(); return result;
}

const interactions = [];
for (const width of [390, 900]) for (const reducedMotion of [false, true]) for (const route of routes) { const row = await interaction(route, width, reducedMotion); interactions.push(row); console.log(`${row.result} interaction=${route.id} width=${width} motion=${reducedMotion ? 'reduce' : 'normal'} rows=${row.open.rows.length} contained=${row.open.backgroundContained} traps=${row.forwardTrap}/${row.reverseTrap} failures=${row.failures.join(',') || 'none'}`); }
await browser.close();

async function contactSheet(name, files) { const cellWidth = 230, labelHeight = 28; const prepared = []; let maxHeight = 0; for (const item of files) { const buffer = await sharp(item.file).resize({ width: cellWidth }).png().toBuffer(); const metadata = await sharp(buffer).metadata(); maxHeight = Math.max(maxHeight, metadata.height); prepared.push({ ...item, buffer }); } const canvas = sharp({ create: { width: cellWidth * prepared.length, height: maxHeight + labelHeight, channels: 4, background: '#eef5fa' } }); const composites = []; for (let index = 0; index < prepared.length; index += 1) { const item = prepared[index]; const safe = item.label.replace(/&/g, '&amp;').replace(/</g, '&lt;'); composites.push({ input: Buffer.from(`<svg width="${cellWidth}" height="${labelHeight}" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" fill="#10263a"/><text x="9" y="19" font-family="Arial" font-size="11" fill="white">${safe}</text></svg>`), left: index * cellWidth, top: 0 }); composites.push({ input: item.buffer, left: index * cellWidth, top: labelHeight }); } const output = path.join(contactRoot, `${name}.png`); await canvas.composite(composites).png().toFile(output); return { path: output, bytes: fs.statSync(output).size, sha256: sha256(output), nonblank: await nonblank(output) }; }
const contacts = [];
for (const width of widths) contacts.push(await contactSheet(`measured-${width}`, routes.map(route => ({ label: route.id, file: path.join(proofRoot, `${route.id}-${width}-top.png`) }))));
for (const width of [390, 900]) for (const reducedMotion of [false, true]) contacts.push(await contactSheet(`menu-${width}-${reducedMotion ? 'reduce' : 'normal'}`, routes.map(route => ({ label: route.id, file: path.join(proofRoot, `${route.id}-${width}-${reducedMotion ? 'reduce' : 'normal'}-menu.png`) }))));

const positiveControls = { missingCaseCaught: 34 !== routes.length * widths.length, rootOverflowCaught: 391 !== 390, generatedOverflowCaught: [{ generated: true }].some(item => item.generated), uncontainedOverflowCaught: [{ generated: false, contained: false }].some(item => !item.generated && !item.contained), sub44Caught: [{ width: 43, height: 44 }].some(item => item.width < 44 || item.height < 44), hiddenSkipCaught: !({ visible: false }).visible, desktopDriftCaught: !sameGeometry({ x: 0 }, { x: 1 }), containmentCaught: !false, reducedMotionCaught: !({ animationName: 'pulse' }).animationName.includes('none') };
positiveControls.result = Object.values(positiveControls).every(Boolean) ? 'PASS' : 'FAIL'; const failures = [...measured, ...interactions].filter(row => row.result === 'FAIL');
fs.writeFileSync(path.join(evidenceRoot, 'browser-qa-r2.json'), `${JSON.stringify({ schema: 'maplemoon-style-chrome-r2-browser-qa/v1', baselineOrigin, r2Origin, routes, widths, measured, interactions, contacts, positiveControls, failures: failures.map(row => ({ route: row.route, width: row.width, reducedMotion: row.reducedMotion, failures: row.failures })) }, null, 2)}\n`);
console.log(`POSITIVE_CONTROLS ${positiveControls.result} count=${Object.keys(positiveControls).length - 1}`); console.log(`BROWSER_QA_R2 ${failures.length ? 'FAIL' : 'PASS'} measured=${measured.length - measured.filter(row => row.result === 'FAIL').length}/${measured.length} interactions=${interactions.length - interactions.filter(row => row.result === 'FAIL').length}/${interactions.length} proofs=${measured.length + interactions.length} contacts=${contacts.length}`); process.exitCode = failures.length || positiveControls.result !== 'PASS' || contacts.some(item => !item.nonblank) ? 1 : 0;
